// Mocks generated by Mockito 5.4.0 from annotations
// in medical_appointment_system/test/modules/usecases/create_appointment_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:medical_appointment_system/modules/clinic/domain/doctor.dart'
    as _i3;
import 'package:medical_appointment_system/modules/clinic/domain/receptionist.dart'
    as _i4;
import 'package:medical_appointment_system/modules/patient/patient.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PatientCopyWith_1<$Res> extends _i1.SmartFake
    implements _i2.$PatientCopyWith<$Res> {
  _Fake$PatientCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$DoctorCopyWith_2<$Res> extends _i1.SmartFake
    implements _i3.$DoctorCopyWith<$Res> {
  _Fake$DoctorCopyWith_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ReceptionistCopyWith_3<$Res> extends _i1.SmartFake
    implements _i4.$ReceptionistCopyWith<$Res> {
  _Fake$ReceptionistCopyWith_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Patient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatient extends _i1.Mock implements _i2.Patient {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  DateTime get birthDate => (super.noSuchMethod(
        Invocation.getter(#birthDate),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#birthDate),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.getter(#birthDate),
        ),
      ) as DateTime);
  @override
  String get medicalPlan => (super.noSuchMethod(
        Invocation.getter(#medicalPlan),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i2.$PatientCopyWith<_i2.Patient> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$PatientCopyWith_1<_i2.Patient>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$PatientCopyWith_1<_i2.Patient>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i2.$PatientCopyWith<_i2.Patient>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [Doctor].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoctor extends _i1.Mock implements _i3.Doctor {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  DateTime get birthDate => (super.noSuchMethod(
        Invocation.getter(#birthDate),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#birthDate),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.getter(#birthDate),
        ),
      ) as DateTime);
  @override
  _i3.$DoctorCopyWith<_i3.Doctor> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$DoctorCopyWith_2<_i3.Doctor>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$DoctorCopyWith_2<_i3.Doctor>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i3.$DoctorCopyWith<_i3.Doctor>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [Receptionist].
///
/// See the documentation for Mockito's code generation for more information.
class MockReceptionist extends _i1.Mock implements _i4.Receptionist {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  DateTime get birthDate => (super.noSuchMethod(
        Invocation.getter(#birthDate),
        returnValue: _FakeDateTime_0(
          this,
          Invocation.getter(#birthDate),
        ),
        returnValueForMissingStub: _FakeDateTime_0(
          this,
          Invocation.getter(#birthDate),
        ),
      ) as DateTime);
  @override
  _i4.$ReceptionistCopyWith<_i4.Receptionist> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$ReceptionistCopyWith_3<_i4.Receptionist>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub:
            _Fake$ReceptionistCopyWith_3<_i4.Receptionist>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i4.$ReceptionistCopyWith<_i4.Receptionist>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
